apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: react-kube-demo-staging
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - PruneLast=true
      - CreateNamespace=true
  destination:
    namespace: react-kube-demo-staging
    server: https://kubernetes.default.svc
  project: default
  source:
    path: kustomize/overlays/staging/
    repoURL: https://github.com/milsman2/react-kube-demo/
    targetRevision: HEAD
    kustomize:
      images:
      - milsman2/react-kube-demo:558b9ca0a1bfe725d5e5691877622d48104d21b6
