apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: react-kube-demo-prod
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - PruneLast=true
      - CreateNamespace=true
  destination:
    namespace: react-kube-demo-production
    server: https://kubernetes.default.svc
  project: default
  source:
    path: kustomize/overlays/production/
    repoURL: https://github.com/milsman2/react-kube-demo/
    targetRevision: HEAD
    kustomize:
      images:
      - milsman2/react-kube-demo:a2d7d7301bc09fe3c88ca0832f8d5d90907d018e
